//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 
namespace BoardGameGeekAPI.BGGObjects {

    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace = "", ElementName = "user", IsNullable = false)]
    public partial class User {

        /// <remarks/>
        [XmlElement("firstname", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userFirstname[] firstname { get; set; }
        
        /// <remarks/>
        [XmlElement("lastname", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userLastname[] lastname { get; set; }

        /// <remarks/>
        [XmlElement("avatarlink", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userAvatarlink[] avatarlink { get; set; }

        /// <remarks/>
        [XmlElement("yearregistered", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userYearregistered[] yearregistered { get; set; }

        /// <remarks/>
        [XmlElement("lastlogin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userLastlogin[] lastlogin { get; set; }

        /// <remarks/>
        [XmlElement("stateorprovince", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userStateorprovince[] stateorprovince { get; set; }

        /// <remarks/>
        [XmlElement("country", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userCountry[] country { get; set; }

        /// <remarks/>
        [XmlElement("webaddress", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userWebaddress[] webaddress { get; set; }

        /// <remarks/>
        [XmlElement("xboxaccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userXboxaccount[] xboxaccount { get; set; }

        /// <remarks/>
        [XmlElement("wiiaccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userWiiaccount[] wiiaccount { get; set; }

        /// <remarks/>
        [XmlElement("psnaccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userPsnaccount[] psnaccount { get; set; }

        /// <remarks/>
        [XmlElement("battlenetaccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userBattlenetaccount[] battlenetaccount { get; set; }

            /// <remarks/>
        [XmlElement("steamaccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userSteamaccount[] steamaccount { get; set; }

        /// <remarks/>
        [XmlElement("traderating", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userTraderating[] traderating { get; set; }

        /// <remarks/>
        [XmlElement("marketrating", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userMarketrating[] marketrating { get; set; }

        /// <remarks/>
        [XmlElement("buddies", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userBuddies[] buddies { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string termsofuse { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string name { get; set; }

        /// <remarks/>
        [XmlAttribute()]
        public string id { get; set; }
    }
}
